networks:
  k6:
  grafana:

services:
  k6:
    image: grafana/k6:1.0.0-rc1
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6-tests:/k6-tests
    depends_on:
      - influxdb
