apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  k6-load-testing-dashboard.json: |
{{ .Files.Get "dashboards/k6-load-testing-dashboard.json" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  dashboard.yaml: |
{{ .Files.Get "dashboards/grafana-dashboard.yaml" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yaml: |
{{ .Files.Get "dashboards/grafana-datasource.yaml" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
data:
  env-config.js: |
{{ .Files.Get "k6-tests/env-config.js" | indent 4 }}
  load-tests.js: |
{{ .Files.Get "k6-tests/load-tests.js" | indent 4 }}
  utils.js: |
{{ .Files.Get "k6-tests/utils.js" | indent 4 }}
