apiVersion: batch/v1
kind: CronJob
metadata:
  name: k6-cronjob
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: k6
        spec:
          restartPolicy: Never
          containers:
          - name: k6
            image: "{{ .Values.k6.image }}"
            ports:
            - containerPort: {{ .Values.k6.port }}
            env:
            - name: K6_OUT
              value: "output-statsd"
            - name: K6_STATSD_ENABLE_TAGS
              value: "true"
            - name: K6_STATSD_ADDR
              value: "datadog-agent.default.svc.cluster.local:8125"
            - name: K6_LOG
              value: "stdout"
            - name: SCENARIO
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: SCENARIO
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: ENV
            - name: RAMP_UP_STEPS
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: RAMP_UP_STEPS
            - name: RAMP_DOWN_STEPS
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: RAMP_DOWN_STEPS
            - name: STEP_DURATION
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: STEP_DURATION
            - name: HOLD_DURATION
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: HOLD_DURATION
            - name: MAX_VUS
              valueFrom:
                secretKeyRef:
                  name: k6
                  key: MAX_VUS
            volumeMounts:
            - name: test-scripts
              mountPath: "{{ .Values.k6.testScriptsPath }}"
            command: [ "k6", "run", "/k6-tests/load-tests.js"]
          volumes:
            - name: test-scripts
              configMap:
                name: k6-scripts
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
