apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
  selector:
    app: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: k6
spec:
  ports:
    - port: 6565
  selector:
    app: k6
